version: 2.1

jobs:
    lint-code:
        docker:
        -   image: borchero/pymaesh:latest
        steps:
        -   checkout
        -   run: pylint pymaesh

    deploy-to-pypi:
        docker:
        -   image: borchero/pymaesh:latest
        steps:
        -   checkout
        -   run: python setup.py sdist bdist_wheel
        -   run: twine upload dist/*

    generate-docs:
        docker:
        -   image: borchero/pymaesh:latest
        steps:
        -   checkout
        -   run: |
                sleep 5
                pip install pymaesh==$CIRCLE_TAG || pip install pymaesh==$CIRCLE_TAG
                cd docs
                sphinx-build . build
        -   persist_to_workspace:
                root: ~/
                paths:
                -   project/docs/build

    deploy-docs:
        docker:
        -   image: borchero/cuckoo:0.4.1
        steps:
        -   attach_workspace:
                at: ~/
        -   run: |
                cd ~/project/docs
                cuckoo auth
                cuckoo publish \
                    --dir build \
                    --bucket pymaesh.borchero.com \
                    --purge \
                    --aws-cloudfront-distribution E31UTD43L8AFI

workflows:
    version: 2
    ci-workflow:
        jobs:
        -   lint-code

    cd-workflow:
        jobs:
        -   deploy-to-pypi:
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
        -   generate-docs:
                requires: 
                -   deploy-to-pypi
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
        -   deploy-docs:
                requires:
                -   generate-docs
                filters:
                    branches:
                        ignore: /.*/
                    tags:
                        only: /.*/
